apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-deployment
 namespace: default
 annotations:
    owner_name: "Vinay Kumar M"
    email-id: "akumarvinayk@gmail.com"
spec:
 replicas: 3
 selector:
   matchLabels:
     app: nginx
 template:
  metadata:
   labels:
     app: nginx
  spec:
    containers:
    - name: my-containers
      image: nginx:1.7.9
      ports:
      - containerPort: 80
    restartPolicy: Always 
