apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-rolling-update
  annotations:
    owner: VinayKumar
    email: vinaykumar.devops@hotmail.com
spec:
  replicas: 3
  selector: 
   matchLabels:
    app: nginx
  template:
   metadata:
     labels:
      app: nginx
   spec:
    containers:
    - name: nginx
      image: nginx:1.7.1
      ports:
      - containerPort: 80
    

