apiVersion: v1
kind: Pod
metadata:
 name: sample-pod
 namespace: default
 labels:
   pod: liveness
spec:
 containers:
 - name: busybox-liveness
   image: busybox
   command: ['sh', '-c', 'sleep 3000']
   livenessProbe:
     exec:
      command:
      - echo
      - "Hello World"
     initialDelaySeconds: 10
     periodSeconds: 5
