apiVersion: v1
kind: Pod
metadata:
 name: multi-container-pod
 labels:
   name: app
 namespace: default
spec:
 containers:
 - name: nginx
   image: nginx
 - name: busybox-sidecar
   image: busybox
   command: ['sh', '-c', 'while true; do sleep 5; done;']

