apiVersion: v1
kind: Pod
metadata:
 name: sample-pod
spec:
 containers:
 - name: sample
   image: busybox
   command: ['sh', '-c', 'sleep 3500']
   volumeMounts:
   - name: my-pvc-vol
     mountPath: /pod/vol
 volumes:
  - name: my-pvc-vol 
    persistentVolumeClaim:
     claimName: my-pvc 
