apiVersion: v1
kind: Pod
metadata:
 name: empty-dir-volume
spec:
 containers:
 - name: sample
   image: busybox
   command: ['sh', '-c', 'sleep 3000']
   volumeMounts:
   - name: my-empty
     mountPath: /tmp/mount
 volumes:
 - name: my-empty
   emptyDir: {}
