apiVersion: v1
kind: Pod
metadata:
 name: cont-port-pod
 labels:
  app: nginx
 namespace: my-ns
spec:
 containers:
 - name: nginx
   image: nginx
   ports:
   - containerPort: 80
 restartPolicy: Never
