apiVersion: v1
kind: Pod
metadata:
 name: my-ns-pod
 namespace: my-ns
 labels:
   app: busy
spec:
 containers:
 - name: sample-cont
   image: busybox
   command:
   - 'sh'
   - '-c'
   - 'echo Hello World && sleep 3600'
