apiVersion: v1
kind: Pod
metadata:
 name: my-securitycontext-pod
 namespace: default
 labels:
   app: busybox
spec:
 securityContext:
  runAsUser: 2000
  fsGroup: 3000
 containers:
 - name: sample-cont
   image: busybox
   command: ['sh', '-c', 'cat /etc/message/message.txt && sleep 600']
   volumeMounts:
   - name: sec-context-vol
     mountPath: /etc/message
 volumes:
 - name: sec-context-vol
   hostPath:
        path: /etc/message
