apiVersion: v1
kind: Pod
metadata: 
 name: my-sample-secret-pod
spec:
 containers:
 - name: sample-busybox
   image: busybox
   command: ['sh', '-c', 'echo Hello && sleep 3000']
   env:
   - name: DB_PASSWORD
     valueFrom:
       secretKeyRef:
         name: my-secret 
         key: password
